version: '3.8'



services:

  jenkins:

    build:

      context: .

      dockerfile: Dockerfile

    container_name: jenkins

    restart: always

    ports:

      - "8080:8080"

      - "50000:50000"

    privileged: true

    environment:

      - "DOCKER_HOST=tcp://docker:2376"

      - "DOCKER_TLS_VERIFY=1"

      - "DOCKER_CERT_PATH=/certs/client"

    volumes:

      - jenkins-data:/var/jenkins_home

      - jenkins-docker-certs:/certs/client:ro

    networks:

      - net

    depends_on:

      - docker



  docker:

    container_name: docker

    image: docker:dind

    restart: always

    privileged: true

    ports:

      - "2375:2375"

      - "2376:2376"

    volumes:

      - jenkins-data:/var/jenkins_home

      - jenkins-docker-certs:/certs/client

    environment:

      - "DOCKER_TLS_CERDIR:/certs"

    networks:

      - net



networks:

  net:



volumes:  # Agregada sección de volúmenes

  jenkins-docker-certs:

  jenkins-data:







