pipeline {
    agent any
    environment{
        IMAGE = 'prueba-node'
        REGISTRY = 'manuBarrionuevo'
        DOCKER_HUB_LOGIN = credentials('docker')
    }
    stages { // el principal donde se arman la tuberia CI
        stage('docker build') {
            steps {
                sh '''
                    VERSION=$(jq --raw-output .version jenkins-test/package.json)
                    echo $VERSION >version.txt
                    docker build -t $IMAGE:$(cat version.txt) .

                    
                   '''
            }
        }
        stage('deploy to hub') {
            steps {
                sh ''' 
                            docker login --username=$DOCKER_HUB_LOGIN_USR --password=$DOCKER_HUB_LOGIN_PSW
                            docker tag prueba-node:v1 $REGISTRY/$IMAGE:$(cat version.txt)
                            docker push $REGISTRY/$IMAGE:$(cat version.txt)
                            '''
                }
        }
    } //fin stage principal
}

